#ifndef CIPR_HTTP_CONFIG_H
#define CIPR_HTTP_CONFIG_H

#ifndef CIPR_HTTP_MAX_CONNECTIONS
#define CIPR_HTTP_MAX_CONNECTIONS 1024
#endif

#ifndef CIPR_HTTP_REQ_BUF_SIZE
#define CIPR_HTTP_REQ_BUF_SIZE 16384
#endif

#ifndef CIPR_HTTP_RES_BUF_SIZE
#define CIPR_HTTP_RES_BUF_SIZE 8192
#endif

#ifndef CIPR_HTTP_HEADER_TIMEOUT_MS
#define CIPR_HTTP_HEADER_TIMEOUT_MS 10000
#endif

#ifndef CIPR_HTTP_BODY_TIMEOUT_MS
#define CIPR_HTTP_BODY_TIMEOUT_MS 30000
#endif

#ifndef CIPR_HTTP_KEEPALIVE_TIMEOUT_MS
#define CIPR_HTTP_KEEPALIVE_TIMEOUT_MS 15000
#endif

#ifndef CIPR_HTTP_MAX_ROUTES
#define CIPR_HTTP_MAX_ROUTES 256
#endif

#ifndef CIPR_HTTP_MAX_CALLBACKS
#define CIPR_HTTP_MAX_CALLBACKS 256
#endif

#ifndef CIPR_HTTP_MAX_PATH_PARAMS
#define CIPR_HTTP_MAX_PATH_PARAMS 16
#endif

#ifndef CIPR_HTTP_MAX_HEADERS
#define CIPR_HTTP_MAX_HEADERS 64
#endif

#ifndef CIPR_HTTP_MAX_HEADER_BYTES
#define CIPR_HTTP_MAX_HEADER_BYTES 16384
#endif

#ifndef CIPR_HTTP_MAX_BODY_BYTES
#define CIPR_HTTP_MAX_BODY_BYTES (8 * 1024 * 1024)
#endif

#ifndef CIPR_HTTP_MAX_PATH_LEN
#define CIPR_HTTP_MAX_PATH_LEN 2048
#endif

#ifndef CIPR_HTTP_MAX_METHOD_LEN
#define CIPR_HTTP_MAX_METHOD_LEN 16
#endif

#ifndef CIPR_HTTP_RATE_BUCKETS
#define CIPR_HTTP_RATE_BUCKETS 4096
#endif

#ifndef CIPR_HTTP_RATE_REFILL_PER_SEC
#define CIPR_HTTP_RATE_REFILL_PER_SEC 100
#endif

#ifndef CIPR_HTTP_RATE_BURST
#define CIPR_HTTP_RATE_BURST 200
#endif

#define AKARI_MAX_CONNECTIONS CIPR_HTTP_MAX_CONNECTIONS
#define AKARI_REQ_BUF_SIZE CIPR_HTTP_REQ_BUF_SIZE
#define AKARI_RES_BUF_SIZE CIPR_HTTP_RES_BUF_SIZE
#define AKARI_HEADER_TIMEOUT_MS CIPR_HTTP_HEADER_TIMEOUT_MS
#define AKARI_BODY_TIMEOUT_MS CIPR_HTTP_BODY_TIMEOUT_MS
#define AKARI_KEEPALIVE_TIMEOUT_MS CIPR_HTTP_KEEPALIVE_TIMEOUT_MS
#define AKARI_MAX_ROUTES CIPR_HTTP_MAX_ROUTES
#define AKARI_MAX_PATH_PARAMS CIPR_HTTP_MAX_PATH_PARAMS
#define AKARI_MAX_HEADERS CIPR_HTTP_MAX_HEADERS
#define AKARI_MAX_HEADER_BYTES CIPR_HTTP_MAX_HEADER_BYTES
#define AKARI_MAX_BODY_BYTES CIPR_HTTP_MAX_BODY_BYTES
#define AKARI_MAX_PATH_LEN CIPR_HTTP_MAX_PATH_LEN
#define AKARI_MAX_METHOD_LEN CIPR_HTTP_MAX_METHOD_LEN
#define AKARI_RATE_BUCKETS CIPR_HTTP_RATE_BUCKETS
#define AKARI_RATE_REFILL_PER_SEC CIPR_HTTP_RATE_REFILL_PER_SEC
#define AKARI_RATE_BURST CIPR_HTTP_RATE_BURST

#endif
